# Generated by Django 5.2.7 on 2025-11-18 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idacudiente', models.IntegerField()),
                ('nom1_acudiente', models.CharField(max_length=20)),
                ('nom2_acudiente', models.CharField(blank=True, max_length=20, null=True)),
                ('ape1_acudiente', models.CharField(max_length=20)),
                ('ape2_acudiente', models.CharField(blank=True, max_length=20, null=True)),
                ('tel_acudiente', models.BigIntegerField()),
                ('parentesco', models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Madrastra', 'Madrastra'), ('Padrastro', 'Padrastro'), ('Tio', 'Tio'), ('Primo', 'Primo'), ('Hermano', 'Hermano'), ('Abuelo', 'Abuelo'), ('Cuidador', 'Cuidador')], max_length=9)),
            ],
            options={
                'db_table': 'acudiente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_persona', models.IntegerField(unique=True)),
                ('tipo_identidad', models.CharField(choices=[('CC', 'CC'), ('TI', 'TI'), ('RC', 'RC'), ('PAS', 'PAS')], max_length=3)),
                ('nom1_persona', models.CharField(max_length=20)),
                ('nom2_persona', models.CharField(blank=True, max_length=20, null=True)),
                ('ape1_persona', models.CharField(max_length=20)),
                ('ape2_persona', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('direc_persona', models.CharField(max_length=40)),
                ('tel_persona', models.BigIntegerField()),
                ('email_persona', models.CharField(max_length=40)),
                ('genero', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('eps', models.CharField(choices=[('Sanitas', 'Sanitas'), ('Sura', 'Sura'), ('Compensar', 'Compensar'), ('Salud Total', 'Salud Total'), ('Famisanar', 'Famisanar'), ('Capital Salud', 'Capital Salud'), ('Aliansalud', 'Aliansalud'), ('Salud Bolivar', 'Salud Bolivar')], max_length=13)),
                ('rh', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('fecha_registro', models.DateField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'persona',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('idasistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asistencia', models.DateTimeField()),
                ('asistencia', models.IntegerField(default=0)),
                ('observaciones', models.TextField()),
            ],
            options={
                'db_table': 'asistencia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nom_categoria', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('identrenamiento', models.AutoField(primary_key=True, serialize=False)),
                ('nom_entrenamiento', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'entrenamiento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('idhabilidad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'habilidad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JornadaEntrenamientos',
            fields=[
                ('idjornada', models.AutoField(primary_key=True, serialize=False)),
                ('dia_jornada', models.CharField(max_length=7)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
            ],
            options={
                'db_table': 'jornada_entrenamientos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Objetivos',
            fields=[
                ('idobjetivos', models.AutoField(primary_key=True, serialize=False)),
                ('nom_objetivo', models.CharField(max_length=70)),
                ('descripcion', models.TextField()),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'objetivos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('idposicion', models.AutoField(primary_key=True, serialize=False)),
                ('nom_posicion', models.CharField(max_length=5)),
                ('desc_posicion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'posicion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('fk_persona_alumno', models.OneToOneField(db_column='fk_persona_alumno', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='partida.persona')),
                ('foto', models.ImageField(null=True, upload_to='fotos/')),
                ('tradatos', models.FileField(db_column='traDatos', null=True, upload_to='traDatos/')),
                ('automedica', models.FileField(db_column='autoMedica', null=True, upload_to='autoMedica/')),
                ('certeps', models.FileField(db_column='certEps', null=True, upload_to='certEps/')),
                ('altura_metros', models.FloatField(null=True)),
                ('peso_medidas', models.FloatField(null=True)),
                ('imc_medidas', models.FloatField(null=True)),
                ('talla', models.CharField(blank=True, choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=4, null=True)),
                ('calzado', models.IntegerField(null=True)),
                ('pie_dominante', models.CharField(choices=[('Derecho', 'Derecho'), ('Izquierdo', 'Izquierdo'), ('Ambidiestro', 'Ambidiestro')], max_length=11, null=True)),
                ('estado_alumno', models.BooleanField(null=True)),
                ('postulante', models.BooleanField(null=True)),
                ('fk_acudiente', models.ForeignKey(db_column='fk_acudiente', on_delete=django.db.models.deletion.CASCADE, to='partida.acudiente')),
                ('fk_posicion', models.ForeignKey(db_column='fk_posicion', on_delete=django.db.models.deletion.CASCADE, to='partida.posicion')),
            ],
            options={
                'db_table': 'alumno',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PersonalT',
            fields=[
                ('fk_persona', models.OneToOneField(db_column='fk_persona', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='partida.persona')),
                ('contrasena', models.CharField(max_length=64)),
                ('tipo_personal', models.CharField(choices=[('Administrador', 'Administrador'), ('Entrenador', 'Entrenador')], max_length=13)),
                ('postulante', models.BooleanField(null=True)),
                ('estado', models.BooleanField(null=True)),
                ('experiencia', models.IntegerField(default=0)),
                ('descripcion_especialidad', models.TextField(null=True)),
                ('hoja_vida', models.FileField(null=True, upload_to='hojaVida/')),
                ('tarjeta_profesional', models.FileField(null=True, upload_to='carnetProfesional/')),
            ],
            options={
                'db_table': 'personal_t',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CalificacionObjetivos',
            fields=[
                ('idcalificacion', models.AutoField(primary_key=True, serialize=False)),
                ('id_objetivo', models.IntegerField()),
                ('evaluacion', models.BooleanField()),
                ('observaciones', models.TextField()),
                ('objetivo_evaluado', models.BooleanField(default=True)),
                ('fk_asistencia', models.ForeignKey(db_column='fk_asistencia', on_delete=django.db.models.deletion.CASCADE, to='partida.asistencia')),
            ],
            options={
                'db_table': 'calificacion_objetivos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CategoriaEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_categoria', models.ForeignKey(db_column='fk_categoria', on_delete=django.db.models.deletion.CASCADE, to='partida.categoria')),
                ('fk_entrenamiento', models.ForeignKey(db_column='fk_entrenamiento', on_delete=django.db.models.deletion.CASCADE, to='partida.entrenamiento')),
            ],
            options={
                'db_table': 'categoria_entrenamiento',
                'managed': True,
                'unique_together': {('fk_categoria', 'fk_entrenamiento')},
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='entrenamiento',
            field=models.ManyToManyField(through='partida.CategoriaEntrenamiento', to='partida.entrenamiento'),
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('idmatricula', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(null=True)),
                ('estado_matricula', models.IntegerField(default=1)),
                ('codigo_renovacion', models.CharField(max_length=20, null=True, unique=True)),
                ('fk_categoria', models.ForeignKey(db_column='fk_categoria', on_delete=django.db.models.deletion.CASCADE, to='partida.categoria')),
                ('fk_alumno', models.ForeignKey(db_column='fk_alumno', on_delete=django.db.models.deletion.CASCADE, to='partida.alumno')),
            ],
            options={
                'db_table': 'matricula',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='asistencia',
            name='fk_matricula_ms',
            field=models.ForeignKey(db_column='fk_matricula_ms', on_delete=django.db.models.deletion.CASCADE, related_name='asistencia_fk_matricula_ms_set', to='partida.matricula'),
        ),
        migrations.CreateModel(
            name='MatriculaSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_matricula', models.ForeignKey(db_column='fk_matricula', on_delete=django.db.models.deletion.CASCADE, to='partida.matricula')),
            ],
            options={
                'db_table': 'matricula_sesion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sesionentrenamiento',
            fields=[
                ('idsesion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrenamiento', models.DateTimeField()),
                ('fk_entrenamiento', models.ForeignKey(db_column='fk_entrenamiento', on_delete=django.db.models.deletion.CASCADE, to='partida.entrenamiento')),
                ('matriculas', models.ManyToManyField(through='partida.MatriculaSesion', to='partida.matricula')),
            ],
            options={
                'db_table': 'sesionentrenamiento',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='matriculasesion',
            name='fk_sesion',
            field=models.ForeignKey(db_column='fk_sesion', on_delete=django.db.models.deletion.CASCADE, to='partida.sesionentrenamiento'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='fk_sesion_ms',
            field=models.ForeignKey(db_column='fk_sesion_ms', on_delete=django.db.models.deletion.CASCADE, to='partida.sesionentrenamiento'),
        ),
        migrations.CreateModel(
            name='EntrenamientoObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_entrenamiento', models.ForeignKey(db_column='fk_entrenamiento', on_delete=django.db.models.deletion.CASCADE, to='partida.entrenamiento')),
                ('fk_objetivo', models.ForeignKey(db_column='fk_objetivo', on_delete=django.db.models.deletion.CASCADE, to='partida.objetivos')),
            ],
            options={
                'db_table': 'entrenamiento_objetivo',
                'managed': True,
                'unique_together': {('fk_entrenamiento', 'fk_objetivo')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='matriculasesion',
            unique_together={('fk_matricula', 'fk_sesion')},
        ),
        migrations.CreateModel(
            name='PersonalTHabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_habilidad', models.ForeignKey(db_column='fk_habilidad', on_delete=django.db.models.deletion.CASCADE, to='partida.habilidad')),
                ('fk_personal', models.ForeignKey(db_column='fk_personal', on_delete=django.db.models.deletion.CASCADE, to='partida.personalt')),
            ],
            options={
                'db_table': 'personal_t_habilidad',
                'managed': True,
                'unique_together': {('fk_personal', 'fk_habilidad')},
            },
        ),
        migrations.CreateModel(
            name='PersonalJornadaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_categoria', models.ForeignKey(db_column='fk_categoria', on_delete=django.db.models.deletion.CASCADE, to='partida.categoria')),
                ('fk_jornada', models.ForeignKey(db_column='fk_jornada', on_delete=django.db.models.deletion.CASCADE, to='partida.jornadaentrenamientos')),
                ('fk_personal', models.ForeignKey(db_column='fk_personal', on_delete=django.db.models.deletion.CASCADE, to='partida.personalt')),
            ],
            options={
                'db_table': 'personal_jornada_categoria',
                'managed': True,
                'unique_together': {('fk_personal', 'fk_jornada', 'fk_categoria')},
            },
        ),
    ]
