# Generated by Django 5.2.7 on 2025-11-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='otraEscuela',
            field=models.FileField(db_column='otraEscuela', null=True, upload_to='otraEscuela/'),
        ),
    ]
