# Generated by Django 5.2.7 on 2025-11-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0002_alumno_otraescuela'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='otraEscuela',
            new_name='otraescuela',
        ),
        migrations.RenameField(
            model_name='matricula',
            old_name='codigo_renovacion',
            new_name='codigo_fin_periodo',
        ),
        migrations.RenameField(
            model_name='matricula',
            old_name='fecha_fin',
            new_name='fecha_terminacion',
        ),
        migrations.AddField(
            model_name='matricula',
            name='fecha_codigo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
