# Generated by Django 5.2.7 on 2025-11-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0003_rename_otraescuela_alumno_otraescuela_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalt',
            name='estado_proceso',
            field=models.CharField(choices=[('postulante', 'Postulante'), ('en_proceso', 'En Proceso'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='postulante', max_length=15),
        ),
    ]
