# Generated by Django 5.2.8 on 2025-11-29 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0004_personalt_estado_proceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalt',
            name='antecedentes',
            field=models.FileField(null=True, upload_to='antecedentes/'),
        ),
        migrations.AddField(
            model_name='personalt',
            name='categoria_experiencia',
            field=models.CharField(choices=[('4 a 7 años', '4 a 7 años'), ('8 a 11 años', '8 a 11 años'), ('12 a 15 años', '12 a 15 años'), ('16 a 17 años', '16 a 17 años'), ('18 a 20 años', '18 a 20 años')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='personalt',
            name='certificado_primeros_auxilios',
            field=models.FileField(null=True, upload_to='primerosAuxilios/'),
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('idexperiencia', models.AutoField(primary_key=True, serialize=False)),
                ('anios_experiencia', models.IntegerField(default=0)),
                ('descripcion', models.TextField()),
                ('fk_persona_experiencia', models.ForeignKey(db_column='fk_persona_experiencia', on_delete=django.db.models.deletion.CASCADE, related_name='experiencias_relacionadas', to='partida.personalt')),
            ],
            options={
                'db_table': 'experiencia',
                'managed': True,
            },
        ),
    ]
