# Generated by Django 5.2.8 on 2025-11-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0005_personalt_antecedentes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='certificado_experiencia',
            field=models.FileField(blank=True, null=True, upload_to='certificadosExperiencia/'),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='nombre_empresa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
