# Generated by Django 5.2.8 on 2025-11-29 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0006_experiencia_certificado_experiencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalt',
            name='categoria_experiencia',
        ),
    ]
