# Generated by Django 5.2.8 on 2025-11-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0009_personalt_categoria_experiencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalt',
            name='descripcion_especialidad',
            field=models.TextField(blank=True, null=True),
        ),
    ]
