# Generated by Django 5.2.7 on 2025-12-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0010_alter_personalt_descripcion_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalt',
            name='categoria_experiencia',
            field=models.CharField(blank=True, choices=[('4 a 7 años', '4 a 7 años'), ('8 a 11 años', '8 a 11 años'), ('12 a 15 años', '12 a 15 años'), ('16 a 17 años', '16 a 17 años'), ('18 años', '18 años')], max_length=30, null=True),
        ),
    ]
