# Generated by Django 5.2.7 on 2025-12-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0012_tokenrecuperacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='limite_alumnos',
            field=models.IntegerField(default=50, help_text='Número máximo de alumnos permitidos en esta categoría'),
        ),
    ]
