# Generated by Django 5.2.7 on 2025-12-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0013_categoria_limite_alumnos'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='documento_identidad',
            field=models.FileField(db_column='documento_identidad', null=True, upload_to='documento_identidad/'),
        ),
    ]
